# This is a basic workflow to help you get started with Actions

name: Build wheels

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"

      - name: Upgrading pip
        run: |
          python -m pip install -U pip setuptools
          python -m pip install wheel
          
      - name: Setup VC++ compiler
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Graphviz
        uses: tlylt/install-graphviz@main

      - name: Install pygraphviz
        run: python -m pip install --use-pep517 `
                  --config-settings="--global-option=build_ext" `
                  --config-settings="--global-option=-IC:\Program Files\Graphviz\include" `
                  --config-settings="--global-option=-LC:\Program Files\Graphviz\lib" `
                  pygraphviz
        
      # Runs a single command using the runners shell
      - name: Build wheels for requirements
        run: python -m pip wheel -w output -r requirements.txt
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "Wheels"
          path: "output"

